### ISSUE TITLE
build kernel error

### ISSUE THREAD

**Issue by OPPO9008** [LinuxPanda/android_kernel_rosy#5]
`CC      arch/arm64/kernel/vdso.o
arch/arm64/kernel/vdso.c: In function 'vdso_init':
arch/arm64/kernel/vdso.c:119:6: warning: 'memcmp' reading 4 bytes from a region of size 1 [-Wstringop-
overflow=]
error, forbidden warning: vdso.c:119
scripts/Makefile.build:257: recipe for target 'arch/arm64/kernel/vdso.o' failed
make[1]: *** [arch/arm64/kernel/vdso.o] Error 1
Makefile:964: recipe for target 'arch/arm64/kernel' failed
make: *** [arch/arm64/kernel] Error 2`

**Comment by LinuxPanda** [comment]
All branches compile fine with gcc 7 for me, so I'm closing this issue.
