### ISSUE TITLE
min freq still forces boost to 1401MHz on input

### ISSUE THREAD

**Issue by zexceed12300** [LinuxPanda/android_kernel_rosy#6]
this is not efficiency.. min freq still force boost to 1401MHz when input though governor changed.

**Comment by LinuxPanda** [comment]
Hi, sorry I was inactive when you opened this bug report and I've moved to 4.9 kernel since few months. Again, I was inactive during the past month due to personal issues. I'm sorry.

I'm archiving this repo for now.
